validate:
  question:
    title:
      maxlength: 350
  answer:
    content:
      maxlength: 150
Admin:
  grammar_exams:
    per_page: 10
  conversation_question:
    num_question: 3
    num_answer: 3
  picture_question:
    num_question: 4
    num_answer: 3
  grammar_question:
    num_question: 1
    num_answer: 4
  grammar_question:
    num_answer: 4
  sign_question:
    num_answer: 3
